
/* Drop Tables */
/*
DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE BBS CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
*/


/* Drop Sequences */

/* DROP SEQUENCE SEQ_LIKES_LNO; */




/* Create Sequences */

CREATE SEQUENCE SEQ_LIKES
		NOCACHE
		NOCYCLE;
		
		CREATE SEQUENCE SEQ_BBS
		NOCACHE
		NOCYCLE;



/* Create Tables */

CREATE TABLE BBS
(
	NO number NOT NULL,
	USERNAME varchar2(10) NOT NULL,
	TITLE nvarchar2(500) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	VISITCOUNT number DEFAULT 0,
	POSTDATE date DEFAULT SYSDATE,
	PRIMARY KEY (NO)
);


CREATE TABLE LIKES
(
	LNO number NOT NULL,
	NO number NOT NULL,
	USERNAME varchar2(10) NOT NULL,
	LIKEDATE date DEFAULT SYSDATE,
	PRIMARY KEY (LNO)
);


CREATE TABLE MEMBER
(
	USERNAME varchar2(10) NOT NULL,
	PASSWORD varchar2(10) NOT NULL,
	GENDER char(1) DEFAULT 'M',
	INTERS varchar2(500),
	EDUCATION nvarchar2(10),
	SELFINTRODUCE nvarchar2(1000),
	REGIDATE date DEFAULT SYSDATE,
	PRIMARY KEY (USERNAME)
);



/* Create Foreign Keys */

ALTER TABLE LIKES
	ADD FOREIGN KEY (NO)
	REFERENCES BBS (NO)
;


ALTER TABLE BBS
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBER (USERNAME)
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (USERNAME)
	REFERENCES MEMBER (USERNAME)
;



